// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba.Data;

#nullable disable

namespace Prueba.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240926153953_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prueba.Entities.Cuarto", b =>
                {
                    b.Property<int>("N_Cuarto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("N_Cuarto"));

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<int?>("LavanderiaN_Servicios")
                        .HasColumnType("int");

                    b.Property<int>("N_servicios")
                        .HasColumnType("int");

                    b.Property<bool>("Uso_Parqueadero")
                        .HasColumnType("bit");

                    b.HasKey("N_Cuarto");

                    b.HasIndex("LavanderiaN_Servicios");

                    b.ToTable("Cuartos");
                });

            modelBuilder.Entity("Prueba.Entities.Lavanderia", b =>
                {
                    b.Property<int>("N_Servicios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("N_Servicios"));

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<int>("N_Cuarto")
                        .HasColumnType("int");

                    b.HasKey("N_Servicios");

                    b.ToTable("lavanderias");
                });

            modelBuilder.Entity("Prueba.Entities.Cuarto", b =>
                {
                    b.HasOne("Prueba.Entities.Lavanderia", "Lavanderia")
                        .WithMany("Cuartos")
                        .HasForeignKey("LavanderiaN_Servicios");

                    b.Navigation("Lavanderia");
                });

            modelBuilder.Entity("Prueba.Entities.Lavanderia", b =>
                {
                    b.Navigation("Cuartos");
                });
#pragma warning restore 612, 618
        }
    }
}
